import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { IoMdAdd, IoMdClose } from "react-icons/io";
import { toast } from "sonner";
import { Pecha } from "@/components/ui/shadimport";
import { Textarea } from "@/components/ui/atoms/textarea";
import { Button } from "@/components/ui/atoms/button";
import ImageContentData from "@/components/ui/molecules/modals/image-upload/ImageContentData";
import { uploadImageToS3 } from "@/components/routes/task/api/taskApi";
import { getApiErrorMessage } from "@/lib/apiErrors";
import { useLanguages } from "@/hooks/useLanguages";
import { ROUTES } from "@/routes/paths";
import type { LanguageCode } from "@/schema/SeriesSchema";
import {
  groupCreateSchema,
  type GroupCoreFormData,
} from "@/schema/GroupSchema";
import {
  buildGroupMetadata,
  createGroup,
  languageLabelForCode,
  type AuthorGroupType,
} from "./api/groupsApi";
import GroupImageField from "./components/GroupImageField";
import { GroupPageShell } from "./components/GroupPageShell";
import GroupTraditionField from "./components/GroupTraditionField";
import { GROUP_KINDS } from "./lib/groupKind";
import { traditionCodeForSave } from "./lib/groupTradition";

/**
 * Create-only form for a practice space or a page; the route decides which.
 * Editing lives on each group section page.
 */
const GroupFormPage = ({
  groupType,
}: Readonly<{ groupType: AuthorGroupType }>) => {
  const kind = GROUP_KINDS[groupType];
  const noun = kind.singular.toLowerCase();
  // A practice space's slug is generated by the backend from its name.
  const asksForSlug = groupType !== "COMMUNITY";
  const navigate = useNavigate();
  const queryClient = useQueryClient();

  const [addedLanguages, setAddedLanguages] = useState<LanguageCode[]>(["EN"]);
  const [avatarPreview, setAvatarPreview] = useState<string | null>(null);
  const [bannerPreview, setBannerPreview] = useState<string | null>(null);
  const [avatarKey, setAvatarKey] = useState<string | null>(null);
  const [bannerKey, setBannerKey] = useState<string | null>(null);
  const [avatarDialogOpen, setAvatarDialogOpen] = useState(false);
  const [bannerDialogOpen, setBannerDialogOpen] = useState(false);
  const [avatarUploading, setAvatarUploading] = useState(false);
  const [bannerUploading, setBannerUploading] = useState(false);
  const { languageOptions } = useLanguages();

  const form = useForm<GroupCoreFormData>({
    resolver: zodResolver(groupCreateSchema),
    defaultValues: {
      slug: "",
      group_type: groupType,
      is_public: true,
      languages: {
        EN: { title: "", sub_title: "", description: "", description_long: "" },
      },
      avatar_key: "",
      banner_key: "",
      tradition_code: "",
    },
  });

  const availableLanguages = languageOptions.filter(
    (l) => !addedLanguages.includes(l.value),
  );

  const addLanguage = (code: LanguageCode) => {
    if (addedLanguages.includes(code)) return;
    setAddedLanguages((prev) => [...prev, code]);
    form.setValue(
      `languages.${code}`,
      { title: "", sub_title: "", description: "", description_long: "" },
      { shouldDirty: true },
    );
  };

  const removeLanguage = (code: LanguageCode) => {
    if (addedLanguages.length <= 1) {
      toast.error("At least one language is required");
      return;
    }
    setAddedLanguages((prev) => prev.filter((c) => c !== code));
    form.unregister(`languages.${code}`);
  };

  const createMutation = useMutation({
    mutationFn: createGroup,
    onSuccess: (data) => {
      toast.success(`${kind.singular} created`, {
        description:
          "It's a draft and isn't visible in the app yet — publish it when you're ready.",
      });
      queryClient.invalidateQueries({ queryKey: ["cms-groups"] });
      navigate(ROUTES.groupEdit(data.id));
    },
    onError: (err) => toast.error(getApiErrorMessage(err)),
  });

  const handleImageUpload = async (file: File, kind: "avatar" | "banner") => {
    const setUploading =
      kind === "avatar" ? setAvatarUploading : setBannerUploading;
    const setPreview = kind === "avatar" ? setAvatarPreview : setBannerPreview;
    const setKey = kind === "avatar" ? setAvatarKey : setBannerKey;
    const setDialog =
      kind === "avatar" ? setAvatarDialogOpen : setBannerDialogOpen;
    const field = kind === "avatar" ? "avatar_key" : "banner_key";

    setUploading(true);
    try {
      const { image, key } = await uploadImageToS3(file, "");
      setPreview(image.original);
      setKey(key);
      form.setValue(field, key, { shouldDirty: true });
      setDialog(false);
      toast.success("Image uploaded");
    } catch {
      toast.error("Failed to upload image");
    } finally {
      setUploading(false);
    }
  };

  const onCreate = form.handleSubmit((data) => {
    const traditionCode = traditionCodeForSave(data.tradition_code);
    createMutation.mutate({
      ...(asksForSlug ? { slug: data.slug.trim() } : {}),
      is_public: data.is_public,
      group_type: data.group_type,
      metadata: buildGroupMetadata(data.languages),
      avatar_key: avatarKey,
      banner_key: bannerKey,
      ...(traditionCode ? { tradition_code: traditionCode } : {}),
    });
  });

  return (
    <GroupPageShell
      backLabel={`← ${kind.plural}`}
      onBack={() => navigate(kind.listPath)}
      title={`Create ${noun}`}
      subtitle={
        <p className="mt-2 text-sm text-muted-foreground">{kind.description}</p>
      }
    >
      <div className="max-w-2xl mx-auto w-full p-4 sm:p-8 pb-12">
        <section className="space-y-6">
          <h2 className="text-base font-bold">General</h2>
          <Pecha.Form {...form}>
            <form onSubmit={onCreate} className="space-y-6">
              {asksForSlug && (
                <Pecha.FormField
                  control={form.control}
                  name="slug"
                  render={({ field }) => (
                    <Pecha.FormItem>
                      <Pecha.FormLabel className="text-sm font-bold">
                        Slug
                        <span className="text-destructive"> *</span>
                      </Pecha.FormLabel>
                      <Pecha.FormControl>
                        <Pecha.Input
                          placeholder="bodhichitta-authors"
                          className="font-mono h-12 bg-white dark:bg-[#262626]"
                          {...field}
                        />
                      </Pecha.FormControl>
                      <Pecha.FormMessage />
                    </Pecha.FormItem>
                  )}
                />
              )}
              <Pecha.FormField
                control={form.control}
                name="is_public"
                render={({ field }) => (
                  <Pecha.FormItem className="flex items-center gap-3">
                    <Pecha.FormControl>
                      <Pecha.Checkbox
                        checked={field.value}
                        onCheckedChange={(checked) =>
                          field.onChange(checked === true)
                        }
                      />
                    </Pecha.FormControl>
                    <Pecha.FormLabel className="text-sm font-bold !mt-0">
                      Public {noun}
                    </Pecha.FormLabel>
                  </Pecha.FormItem>
                )}
              />
              <GroupTraditionField form={form} />
              <div className="space-y-4">
                {addedLanguages.map((code) => (
                  <div
                    key={code}
                    className="relative rounded-lg border border-input bg-[#FAFAFA] dark:bg-[#262626] p-4 space-y-3"
                  >
                    <button
                      type="button"
                      onClick={() => removeLanguage(code)}
                      className="absolute top-2 right-2 text-muted-foreground hover:text-foreground p-1"
                      aria-label={`Remove ${languageLabelForCode(code)}`}
                    >
                      <IoMdClose className="h-4 w-4" />
                    </button>
                    <Pecha.FormField
                      control={form.control}
                      name={`languages.${code}.title`}
                      render={({ field }) => (
                        <Pecha.FormItem>
                          <Pecha.FormLabel className="text-sm font-bold">
                            {languageLabelForCode(code)} title
                            <span className="text-destructive"> *</span>
                          </Pecha.FormLabel>
                          <Pecha.FormControl>
                            <Pecha.Input
                              className="h-12 bg-white dark:bg-[#181818]"
                              {...field}
                            />
                          </Pecha.FormControl>
                          <Pecha.FormMessage />
                        </Pecha.FormItem>
                      )}
                    />
                    <Pecha.FormField
                      control={form.control}
                      name={`languages.${code}.sub_title`}
                      render={({ field }) => (
                        <Pecha.FormItem>
                          <Pecha.FormLabel className="text-sm font-bold">
                            {languageLabelForCode(code)} sub-title
                            <span className="text-destructive"> *</span>
                          </Pecha.FormLabel>
                          <Pecha.FormControl>
                            <Pecha.Input
                              className="h-12 bg-white dark:bg-[#181818]"
                              {...field}
                            />
                          </Pecha.FormControl>
                          <Pecha.FormMessage />
                        </Pecha.FormItem>
                      )}
                    />
                    <Pecha.FormField
                      control={form.control}
                      name={`languages.${code}.description`}
                      render={({ field }) => (
                        <Pecha.FormItem>
                          <Pecha.FormLabel className="text-sm font-bold">
                            {languageLabelForCode(code)} description
                            <span className="text-destructive"> *</span>
                          </Pecha.FormLabel>
                          <Pecha.FormControl>
                            <Textarea
                              className="min-h-[100px] resize-none bg-white dark:bg-[#181818]"
                              maxLength={200}
                              {...field}
                            />
                          </Pecha.FormControl>
                          <Pecha.FormMessage />
                        </Pecha.FormItem>
                      )}
                    />
                    <Pecha.FormField
                      control={form.control}
                      name={`languages.${code}.description_long`}
                      render={({ field }) => (
                        <Pecha.FormItem>
                          <Pecha.FormLabel className="text-sm font-bold">
                            {languageLabelForCode(code)} long description
                          </Pecha.FormLabel>
                          <Pecha.FormControl>
                            <Textarea
                              className="min-h-[160px] resize-y bg-white dark:bg-[#181818]"
                              placeholder="A longer description with more detail…"
                              {...field}
                            />
                          </Pecha.FormControl>
                          <Pecha.FormMessage />
                        </Pecha.FormItem>
                      )}
                    />
                  </div>
                ))}
              </div>
              {availableLanguages.length > 0 && (
                <Pecha.Select
                  onValueChange={(v) => addLanguage(v as LanguageCode)}
                >
                  <Pecha.SelectTrigger className="w-fit border-dashed bg-white dark:bg-[#262626]">
                    <div className="flex items-center gap-2 text-muted-foreground">
                      <IoMdAdd className="h-4 w-4" />
                      <Pecha.SelectValue placeholder="Add language" />
                    </div>
                  </Pecha.SelectTrigger>
                  <Pecha.SelectContent>
                    {availableLanguages.map((lang) => (
                      <Pecha.SelectItem key={lang.value} value={lang.value}>
                        {lang.label}
                      </Pecha.SelectItem>
                    ))}
                  </Pecha.SelectContent>
                </Pecha.Select>
              )}
              <div className="grid sm:grid-cols-2 gap-6">
                <GroupImageField
                  label="Avatar"
                  displayUrl={avatarPreview}
                  hasStoredImage={Boolean(avatarKey)}
                  onUploadClick={() => setAvatarDialogOpen(true)}
                  imageClassName="w-20 h-20 rounded-full object-cover border"
                />
                <GroupImageField
                  label="Banner"
                  displayUrl={bannerPreview}
                  hasStoredImage={Boolean(bannerKey)}
                  onUploadClick={() => setBannerDialogOpen(true)}
                  imageClassName="w-full max-w-xs h-24 rounded object-cover border"
                />
              </div>
              <div className="flex justify-end pt-2">
                <Button
                  type="submit"
                  className="bg-[#A51C21] text-white hover:bg-[#A51C21]/90"
                  disabled={createMutation.isPending}
                >
                  {createMutation.isPending ? "Creating…" : `Create ${noun}`}
                </Button>
              </div>
            </form>
          </Pecha.Form>
        </section>
      </div>

      <Pecha.Dialog open={avatarDialogOpen} onOpenChange={setAvatarDialogOpen}>
        <Pecha.DialogContent>
          <Pecha.DialogHeader>
            <Pecha.DialogTitle>Upload avatar</Pecha.DialogTitle>
          </Pecha.DialogHeader>
          <ImageContentData
            onUpload={(file) => handleImageUpload(file, "avatar")}
            isLoading={avatarUploading}
          />
        </Pecha.DialogContent>
      </Pecha.Dialog>

      <Pecha.Dialog open={bannerDialogOpen} onOpenChange={setBannerDialogOpen}>
        <Pecha.DialogContent>
          <Pecha.DialogHeader>
            <Pecha.DialogTitle>Upload banner</Pecha.DialogTitle>
          </Pecha.DialogHeader>
          <ImageContentData
            onUpload={(file) => handleImageUpload(file, "banner")}
            isLoading={bannerUploading}
          />
        </Pecha.DialogContent>
      </Pecha.Dialog>
    </GroupPageShell>
  );
};

export default GroupFormPage;
