import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { useTranslate } from "@tolgee/react";
import { Pecha } from "@/components/ui/shadimport";
import { Button } from "@/components/ui/atoms/button";
import ImageContentData from "@/components/ui/molecules/modals/image-upload/ImageContentData";
import { uploadImageToS3 } from "@/components/routes/task/api/taskApi";
import { getApiErrorMessage } from "@/lib/apiErrors";
import { useLanguages } from "@/hooks/useLanguages";
import { ROUTES } from "@/routes/paths";
import type { LanguageCode } from "@/schema/SeriesSchema";
import {
  groupCreateSchema,
  type GroupCoreFormData,
} from "@/schema/GroupSchema";
import {
  buildGroupMetadata,
  createGroup,
  type AuthorGroupType,
} from "./api/groupsApi";
import GroupImageField from "./components/GroupImageField";
import GroupLanguageTabs from "./components/GroupLanguageTabs";
import { GroupPageShell } from "./components/GroupPageShell";
import GroupTraditionField from "./components/GroupTraditionField";
import { GROUP_KINDS } from "./lib/groupKind";
import { traditionCodeForSave } from "./lib/groupTradition";

/**
 * Create-only form for a practice space or a page; the route decides which.
 * Editing lives on each group section page.
 */
const GroupFormPage = ({
  groupType,
}: Readonly<{ groupType: AuthorGroupType }>) => {
  const { t } = useTranslate();
  const kind = GROUP_KINDS[groupType];
  const isCommunity = groupType === "COMMUNITY";
  const createLabel = t(
    isCommunity
      ? "studio.groups.pages.form.create_community"
      : "studio.groups.pages.form.create_page",
  );
  // A practice space's slug is generated by the backend from its name.
  const asksForSlug = groupType !== "COMMUNITY";
  const navigate = useNavigate();
  const queryClient = useQueryClient();

  const [addedLanguages, setAddedLanguages] = useState<LanguageCode[]>(["EN"]);
  const [avatarPreview, setAvatarPreview] = useState<string | null>(null);
  const [bannerPreview, setBannerPreview] = useState<string | null>(null);
  const [avatarKey, setAvatarKey] = useState<string | null>(null);
  const [bannerKey, setBannerKey] = useState<string | null>(null);
  const [avatarDialogOpen, setAvatarDialogOpen] = useState(false);
  const [bannerDialogOpen, setBannerDialogOpen] = useState(false);
  const [avatarUploading, setAvatarUploading] = useState(false);
  const [bannerUploading, setBannerUploading] = useState(false);
  const { languageOptions } = useLanguages();

  const form = useForm<GroupCoreFormData>({
    resolver: zodResolver(groupCreateSchema),
    defaultValues: {
      slug: "",
      group_type: groupType,
      is_public: true,
      languages: {
        EN: { title: "", sub_title: "", description: "", description_long: "" },
      },
      avatar_key: "",
      banner_key: "",
      tradition_code: "",
    },
  });

  const availableLanguages = languageOptions.filter(
    (l) => !addedLanguages.includes(l.value),
  );

  const addLanguage = (code: LanguageCode) => {
    if (addedLanguages.includes(code)) return;
    setAddedLanguages((prev) => [...prev, code]);
    form.setValue(
      `languages.${code}`,
      { title: "", sub_title: "", description: "", description_long: "" },
      { shouldDirty: true },
    );
  };

  const removeLanguage = (code: LanguageCode) => {
    if (addedLanguages.length <= 1) {
      toast.error(t("studio.groups.pages.form.language_required"));
      return;
    }
    setAddedLanguages((prev) => prev.filter((c) => c !== code));
    form.unregister(`languages.${code}`);
  };

  const createMutation = useMutation({
    mutationFn: createGroup,
    onSuccess: (data) => {
      toast.success(
        t(
          isCommunity
            ? "studio.groups.pages.form.created_community"
            : "studio.groups.pages.form.created_page",
        ),
        {
          description: t("studio.groups.pages.form.created_draft_description"),
        },
      );
      queryClient.invalidateQueries({ queryKey: ["cms-groups"] });
      navigate(ROUTES.groupEdit(data.id));
    },
    onError: (err) => toast.error(getApiErrorMessage(err)),
  });

  const handleImageUpload = async (file: File, kind: "avatar" | "banner") => {
    const setUploading =
      kind === "avatar" ? setAvatarUploading : setBannerUploading;
    const setPreview = kind === "avatar" ? setAvatarPreview : setBannerPreview;
    const setKey = kind === "avatar" ? setAvatarKey : setBannerKey;
    const setDialog =
      kind === "avatar" ? setAvatarDialogOpen : setBannerDialogOpen;
    const field = kind === "avatar" ? "avatar_key" : "banner_key";

    setUploading(true);
    try {
      const { image, key } = await uploadImageToS3(file, "");
      setPreview(image.original);
      setKey(key);
      form.setValue(field, key, { shouldDirty: true });
      setDialog(false);
      toast.success(t("studio.groups.pages.form.image_uploaded"));
    } catch {
      toast.error(t("studio.groups.pages.form.image_upload_failed"));
    } finally {
      setUploading(false);
    }
  };

  const onCreate = form.handleSubmit((data) => {
    const traditionCode = traditionCodeForSave(data.tradition_code);
    createMutation.mutate({
      ...(asksForSlug ? { slug: data.slug.trim() } : {}),
      is_public: data.is_public,
      group_type: data.group_type,
      metadata: buildGroupMetadata(data.languages),
      avatar_key: avatarKey,
      banner_key: bannerKey,
      ...(traditionCode ? { tradition_code: traditionCode } : {}),
    });
  });

  return (
    <GroupPageShell
      backLabel={`← ${t(
        isCommunity
          ? "studio.groups.pages.layout.back_label_community"
          : "studio.groups.pages.layout.back_label_page",
      )}`}
      onBack={() => navigate(kind.listPath)}
      title={createLabel}
      subtitle={
        <p className="mt-2 text-sm text-muted-foreground">
          {t(
            isCommunity
              ? "studio.groups.pages.form.kind_description_community"
              : "studio.groups.pages.form.kind_description_page",
          )}
        </p>
      }
    >
      <div className="max-w-2xl mx-auto w-full p-4 sm:p-8 pb-12">
        <section className="space-y-6">
          <h2 className="text-base font-bold">
            {t("studio.groups.pages.form.general_heading")}
          </h2>
          <Pecha.Form {...form}>
            <form onSubmit={onCreate} className="space-y-6">
              {asksForSlug && (
                <Pecha.FormField
                  control={form.control}
                  name="slug"
                  render={({ field }) => (
                    <Pecha.FormItem>
                      <Pecha.FormLabel className="text-sm font-bold">
                        {t("studio.groups.pages.form.slug_label")}
                        <span className="text-destructive"> *</span>
                      </Pecha.FormLabel>
                      <Pecha.FormControl>
                        <Pecha.Input
                          placeholder="bodhichitta-authors"
                          className="font-mono h-12 bg-white dark:bg-[#262626]"
                          {...field}
                        />
                      </Pecha.FormControl>
                      <Pecha.FormMessage />
                    </Pecha.FormItem>
                  )}
                />
              )}
              <Pecha.FormField
                control={form.control}
                name="is_public"
                render={({ field }) => (
                  <Pecha.FormItem className="flex items-center gap-3">
                    <Pecha.FormControl>
                      <Pecha.Checkbox
                        checked={field.value}
                        onCheckedChange={(checked) =>
                          field.onChange(checked === true)
                        }
                      />
                    </Pecha.FormControl>
                    <Pecha.FormLabel className="text-sm font-bold !mt-0">
                      {t(
                        isCommunity
                          ? "studio.groups.pages.form.public_community"
                          : "studio.groups.pages.form.public_page",
                      )}
                    </Pecha.FormLabel>
                  </Pecha.FormItem>
                )}
              />
              <GroupTraditionField form={form} />
              <GroupLanguageTabs
                form={form}
                languages={addedLanguages}
                availableLanguages={availableLanguages}
                onAddLanguage={addLanguage}
                onRemoveLanguage={removeLanguage}
              />
              <div className="grid sm:grid-cols-2 gap-6">
                <GroupImageField
                  label={t("studio.groups.pages.form.avatar_label")}
                  displayUrl={avatarPreview}
                  hasStoredImage={Boolean(avatarKey)}
                  onUploadClick={() => setAvatarDialogOpen(true)}
                  imageClassName="w-20 h-20 rounded-full object-cover border"
                />
                <GroupImageField
                  label={t("studio.groups.pages.form.banner_label")}
                  displayUrl={bannerPreview}
                  hasStoredImage={Boolean(bannerKey)}
                  onUploadClick={() => setBannerDialogOpen(true)}
                  imageClassName="w-full max-w-xs h-24 rounded object-cover border"
                />
              </div>
              <div className="flex justify-end pt-2">
                <Button
                  type="submit"
                  className="bg-[#A51C21] text-white hover:bg-[#A51C21]/90"
                  disabled={createMutation.isPending}
                >
                  {createMutation.isPending
                    ? t("studio.common.creating")
                    : createLabel}
                </Button>
              </div>
            </form>
          </Pecha.Form>
        </section>
      </div>

      <Pecha.Dialog open={avatarDialogOpen} onOpenChange={setAvatarDialogOpen}>
        <Pecha.DialogContent>
          <Pecha.DialogHeader>
            <Pecha.DialogTitle>
              {t("studio.groups.pages.form.upload_avatar")}
            </Pecha.DialogTitle>
          </Pecha.DialogHeader>
          <ImageContentData
            onUpload={(file) => handleImageUpload(file, "avatar")}
            isLoading={avatarUploading}
          />
        </Pecha.DialogContent>
      </Pecha.Dialog>

      <Pecha.Dialog open={bannerDialogOpen} onOpenChange={setBannerDialogOpen}>
        <Pecha.DialogContent>
          <Pecha.DialogHeader>
            <Pecha.DialogTitle>
              {t("studio.groups.pages.form.upload_banner")}
            </Pecha.DialogTitle>
          </Pecha.DialogHeader>
          <ImageContentData
            onUpload={(file) => handleImageUpload(file, "banner")}
            isLoading={bannerUploading}
          />
        </Pecha.DialogContent>
      </Pecha.Dialog>
    </GroupPageShell>
  );
};

export default GroupFormPage;
