import { z } from "zod";
import type { LanguageCode } from "@/lib/languageCodes";

export type GroupLanguageCode = LanguageCode;

/** One language's text. Only the title is required, in every language; the
 *  sub-title and both descriptions may be left empty. */
export const groupLanguageBlockSchema = z.object({
  title: z.string().trim().min(1, "Title is required"),
  sub_title: z.string().trim().optional(),
  description: z
    .string()
    .trim()
    .max(200, "Description must be 200 characters or less")
    .optional(),
  description_long: z.string().trim().optional(),
});

export const authorGroupTypeSchema = z.enum(["PAGE", "COMMUNITY"]);

export type AuthorGroupType = z.infer<typeof authorGroupTypeSchema>;

/** Underscores are allowed because generated slugs end in one: "dharma-circle_4821". */
const SLUG_PATTERN = /^[a-z0-9]+(?:[-_][a-z0-9]+)*$/;

const groupCoreFields = z.object({
  slug: z.string().trim(),
  group_type: authorGroupTypeSchema,
  is_public: z.boolean(),
  languages: z.record(z.string(), groupLanguageBlockSchema),
  avatar_key: z.string().optional(),
  banner_key: z.string().optional(),
  /** "" means no tradition. */
  tradition_code: z.string().optional(),
});

type GroupCoreFields = z.infer<typeof groupCoreFields>;

const refineGroupCore =
  (slugRequired: (data: GroupCoreFields) => boolean) =>
  (data: GroupCoreFields, ctx: z.RefinementCtx) => {
    const present = Object.keys(data.languages).filter(
      (code) => data.languages[code] != null,
    );
    if (present.length < 1) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "Add at least one language",
        path: ["languages"],
      });
    }
    if (!data.slug) {
      if (slugRequired(data)) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: "Slug is required",
          path: ["slug"],
        });
      }
    } else if (!SLUG_PATTERN.test(data.slug)) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message:
          "Use lowercase letters, numbers, hyphens, and underscores only",
        path: ["slug"],
      });
    }
  };

/** Editing a group: every group already has a slug, so it stays required. */
export const groupCoreSchema = groupCoreFields.superRefine(
  refineGroupCore(() => true),
);

/**
 * Creating a group: a practice space gets its slug generated by the backend
 * from its name ("dharma-circle_4821"), so only pages ask for one.
 */
export const groupCreateSchema = groupCoreFields.superRefine(
  refineGroupCore((data) => data.group_type !== "COMMUNITY"),
);

export type GroupCoreFormData = z.infer<typeof groupCoreSchema>;

export const groupSocialLinkSchema = z.object({
  platform: z.string().min(1),
  url: z.string().url("Enter a valid URL"),
});

export type GroupSocialLinkFormData = z.infer<typeof groupSocialLinkSchema>;
